// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Counter: typeof import('./core/components/Counter.vue')['default']
    Footer: typeof import('./core/components/Footer.vue')['default']
    'IconCarbon:campsite': typeof import('~icons/carbon/campsite')['default']
    'IconCarbon:dicomOverlay': typeof import('~icons/carbon/dicom-overlay')['default']
    'IconCarbon:language': typeof import('~icons/carbon/language')['default']
    'IconCarbon:logoGithub': typeof import('~icons/carbon/logo-github')['default']
    'IconCarbon:moon': typeof import('~icons/carbon/moon')['default']
    'IconCarbon:pedestrian': typeof import('~icons/carbon/pedestrian')['default']
    'IconCarbon:sun': typeof import('~icons/carbon/sun')['default']
    'IconCarbon:warning': typeof import('~icons/carbon/warning')['default']
    README: typeof import('./core/components/README.md')['default']
  }
}

export { }
