// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BalanceNumber: typeof import('./core/components/number/BalanceNumber.vue')['default']
    BaseBtn: typeof import('./core/components/button/BaseBtn.vue')['default']
    BlobMask: typeof import('./core/components/BlobMask.vue')['default']
    CurrencyNumber: typeof import('./core/components/number/CurrencyNumber.vue')['default']
    DefaultAside: typeof import('./core/components/layouts/default/DefaultAside.vue')['default']
    DefaultFooter: typeof import('./core/components/layouts/default/DefaultFooter.vue')['default']
    DefaultHeader: typeof import('./core/components/layouts/default/DefaultHeader.vue')['default']
    FullTextCountdown: typeof import('./core/components/countdown/FullTextCountdown.vue')['default']
    HomeAboutBlob: typeof import('./home/components/about/HomeAboutBlob.vue')['default']
    HomeAboutContent: typeof import('./home/components/about/HomeAboutContent.vue')['default']
    HomeAboutSection: typeof import('./home/components/about/HomeAboutSection.vue')['default']
    HomeFooter: typeof import('./core/components/layouts/home/HomeFooter.vue')['default']
    HomeHeader: typeof import('./core/components/layouts/home/HomeHeader.vue')['default']
    HomeHeaderItem: typeof import('./core/components/layouts/home/HomeHeaderItem.vue')['default']
    HomeHeroParallax: typeof import('./home/components/hero/HomeHeroParallax.vue')['default']
    HomeHeroSection: typeof import('./home/components/hero/HomeHeroSection.vue')['default']
    LangSelect: typeof import('./core/components/LangSelect.vue')['default']
    Link: typeof import('./core/components/Link.vue')['default']
    Logo: typeof import('./core/components/Logo.vue')['default']
    Number: typeof import('./core/components/number/Number.vue')['default']
    README: typeof import('./core/components/README.md')['default']
    TextCountdown: typeof import('./core/components/countdown/TextCountdown.vue')['default']
  }
}

export { }
